#!/usr/bin/env bash

brew bundle

# install Homebrew if it is not installed (https://brew.sh/)
if [ ! -x "$(command -v brew)" ]; then
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
fi

export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}"

# install Hasklug Nerd Font
if [[ ! -f "~/Library/Fonts/HasklugNerdFontMono-Regular.ttf" ]]; then
  ( # do in the subshell to not loose the current directory
    cd /tmp
    curl -fsSL \
      https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hasklig.zip \
    | tar xzf -  
    mkdir -p ~/Library/Fonts
    mv Hasklug*.otf ~/Library/Fonts
    echo "installed Hasklug Nerd Font"
  )
fi

# setup paths for google cloud sdk
source "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.bash.inc"

# completion for bitwraden-cli are not working by default 
# because they just miss the activation of compdef.
BW_COMPLETION_FILE=$(brew --prefix)/share/zsh/site-functions/_bitwarden-cli
# ensure that we don't add this line twice
sed -i '/^compdef _bw bw$/d' ${BW_COMPLETION_FILE}
# actually add the missing line
sed -i 's/^\(#compdef _bw bw\)$/\1\n\ncompdef _bw bw\n/' ${BW_COMPLETION_FILE}

# setting up gpg https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e
if [[ ! -d ~/.gnupg ]]; then
  mkdir ~/.gnupg
  echo "pinentry-program $(brew --prefix)/bin/pinentry-mac" >| ~/.gnupg/gpg-agent.conf
  echo 'use-agent' >| ~/.gnupg/gpg.conf
  chmod 700 ~/.gnupg
fi

# setup python
pyenv install 3.11
pyenv global 3.11

