#!/usr/bin/env bash
# set -eu -o pipefail

if [[ $(uname) == "Darwin" ]]; then
  source install-darwin
  # TODO: need to start hammerspoon somehow after the installation
fi

# install rustup if not installed already
if [[ ! -x "$(command -v rustup)" ]]; then
  curl --proto '=https' \
    --tlsv1.2 \
    -sSf \
    https://sh.rustup.rs | bash -s - -y -q
  mkdir -p ~/.local/share/zsh/completion
  rustup completions zsh >| ~/.local/share/zsh/completion/_rustup
  rustup completions zsh cargo >| ~/.local/share/zsh/completion/_cargo
fi

source replace

( # set initial fzf colorscheme to be light
cd ~/.config/fzf
ln -sf themes/rose-pine-dawn.sh current-theme.zsh
)

# set initial kitty colorsheme to be light
kitty +kitten themes --config-file-name=themes.conf --reload-in=all Rosé Pine Dawn

( # set up the virtual environment for neovim
  pyenv virtualenv 3.12.1 neovim
  pyenv activate neovim
  pip install pynvim
  # additional dependencies for copilot chat
  pip install python-dotenv requests prompt-toolkit
)
