#!/usr/bin/env bash
# set -eu -o pipefail

function replace() {
  local SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
  local TARGET=$(realpath --no-symlinks ${1})
  local SOURCE="${SCRIPT_DIR}/$(echo ${TARGET} | sed s#^${HOME}#home#)"
  echo "source: ${SOURCE}"
  echo "target: ${TARGET}"
  if [[ ! -e "${SOURCE}" ]]; then
    echo "replace: source ${SOURCE} does not exist"
    return 1
  fi
  if [[ -L "${TARGET}" ]]; then
    local previous_source=$(readlink "${TARGET}")
    if [[ "${previous_source}" == "${SOURCE}" ]]; then
      echo "replace: ${TARGET} already points to ${SOURCE}"
      return 0
    fi
    echo "replace: created ${TARGET}.backup"
    mv "${TARGET}" "${TARGET}.backup"
  elif [[ -d "${TARGET}" ]]; then
    echo "replace: created ${TARGET}.backup"
    mv "${TARGET}" "${TARGET}.backup"
  elif [[ -f "${TARGET}" ]]; then
    echo "replace: created ${TARGET}.backup"
    mv "${TARGET}" "${TARGET}.backup"
  elif [[ -e "${TARGET}" ]]; then
    echo "replace: cannot replace special file: ${TARGET}"
    return 1
  fi
  mkdir -p "$(dirname "${TARGET}")"
  ln -s "${SOURCE}" "${TARGET}"
}

replace ~/.zshrc
replace ~/.zimrc
replace ~/.p10k.zsh
replace ~/.config/bat
replace ~/.config/fd
replace ~/.config/fzf
replace ~/.config/git
replace ~/.config/kitty
replace ~/.config/tmux
replace ~/.config/zsh
replace ~/.config/nvim
replace ~/.config/hammerspoon
