# start window numbers at 1 to match keyboard order with tmux window order
set-option -g base-index 1
# use utf-8
# set-option -g status-utf8 on

# rebind default prefix
unbind C-b
set -g prefix C-s
setw -g mode-keys vi

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# No delay for escape key press
set -sg escape-time 0

# reload config faster
bind R source-file ~/.tmux.conf \; \
	display-message "config reloaded reloaded..."

# enable and disable activity monitor
bind a set-window-option monitor-activity on \; \
	display-message "monitoring activity on"

bind A set-window-option monitor-activity off \; \
	display-message "monitoring activity off"
bind M-j command-prompt -p "join pane from:"  "join-pane -s ':%%'"
bind M-s command-prompt -p "send pane to:"  "join-pane -t ':%%'"

# STATUSLINE
set-option -g status-left " #H:#S) "
set-option -g status-left-length 24
set-option -g status-right " %a-%d-%b %T "
set-option -g status-left-length 24
set-option -g status-justify centre

# WINDOWS
set-window-option -g window-status-current-format "[#I:#W]"
set-window-option -g window-status-format " #I:#W "
set-window-option -g alternate-screen on

# COLORS
set-option -g default-terminal "screen-256color"

#####################################################
# BASE16 https://github.com/chriskempson/base16     #
#                                                   #
# base00 colour00                                   #
# base01 colour18                                   #
# base02 colour19                                   #
# base03 colour08                                   #
# base04 colour20                                   #
# base05 colour07                                   #
# base06 colour21                                   #
# base07 colour15                                   #
# base08 colour01 colour09                          #
# base09 colour16                                   #
# base0A colour03 colour11                          #
# base0B colour02 colour10                          #
# base0C colour06 colour14                          #
# base0D colour04 colour12                          #
# base0E colour05 colour13                          #
# base0F colour17                                   #
#####################################################

# default statusbar colors
set-option -g status-bg colour18  # BASE01
set-option -g status-fg colour07  # BASE05
set-option -g status-attr none

# default window title colors
set-window-option -g window-status-bg colour18 # BASE01
set-window-option -g window-status-fg colour07 # BASE05

# active window title colors
set-window-option -g window-status-current-bg colour18 # BASE01
set-window-option -g window-status-current-fg colour03 # BASE0A
set-window-option -g window-status-current-attr bold

# pane border
set-option -g pane-border-fg colour04 # BASE0D
set-option -g pane-active-border-fg colour03 # BASE0A

# message text
set-option -g message-bg colour18 # BASE01
set-option -g message-fg colour03 # BASE0A

# pane number display
set-option -g display-panes-active-colour colour03 # BASE0A
set-option -g display-panes-colour colour04 # BASE0D

# clock
set-window-option -g clock-mode-colour colour03 # BASE0A
