alias ls="gls --color --group-directories-first -F"
alias l="gls --color --group-directories-first -Fl"
alias ll="gls --color --group-directories-first --time-style=long-iso -Fl"
alias la="gls --color --group-directories-first --time-style=long-iso -Fla"
alias lah="gls --color --group-directories-first --time-style=long-iso -Flah"
alias grep="ggrep --color=auto"
alias date="gdate"
