font_family      Fira Code
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size        12.0

cursor_shape          block
cursor_blink_interval 0     

remember_window_size   no
initial_window_width   1640
initial_window_height  840

###
# Solorized dark color scheme
###

# black
color0   #073642
color8   #002b36

# red
color1   #dc322f
color9   #cb4b16

# green
color2   #859900
color10  #586e75

# yellow
color3   #b58900
color11  #657b83

# blue
color4  #268bd2
color12 #839496

# magenta
color5   #d33682
color13  #6c71c4

# cyan
color6   #2aa198
color14  #93a1a1

# white
color7   #839496
color15  #fdf6e3

# -- misc --

foreground              #839495
background              #002b36
selection_foreground    #93a1a1
selection_background    #073642
cursor                  #93a1a1
active_border_color     #00ff00
inactive_border_color   #cccccc
active_tab_foreground   #000
active_tab_background   #eee
inactive_tab_foreground #444
inactive_tab_background #999
