font_family      Fira Code
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size        12.0

cursor_shape          block
cursor_blink_interval 0

enable_audio_bell no

remember_window_size   no
initial_window_width   1640
initial_window_height  840

#
# --- Solorized dark color scheme
#

# base02  (black)
color0    #073642

# base03  (black bright)
color8    #002b36

# red     (red)
color1    #dc322f

# orange  (red bright)
color9    #cb4b16

# green   (green)
color2    #859900

# base01  (green bright)
color10   #586e75

# yellow  (yellow)
color3    #b58900

# base00  (yellow bright)
color11   #657b83

# blue    (blue)
color4    #268bd2

# base0   (blue bright)
color12   #839496

# magenta (magenta)
color5    #d33682

# violet  (magenta bright)
color13   #6c71c4

# cyan    (cyan)
color6    #2aa198

# base1   (cyan bright)
color14   #93a1a1

# base0   (white)
color7    #839496

# base3   (white bright)
color15   #fdf6e3

#
# --- Misc
#

foreground              #839495
background              #073642

selection_foreground    #073642
selection_background    #eee8d5

cursor                  #839496
focus_follows_mouse     yes

active_border_color     #00ff00
inactive_border_color   #cccccc

active_tab_foreground   #000
active_tab_background   #eee

inactive_tab_foreground #444
inactive_tab_background #999
