# vim: ft=tmux ts=2 sw=2

# === pane borders

set -g pane-border-lines single
set -g pane-border-status off
set -g pane-border-indicators colour

set -g pane-border-style bg=$color_border_bg,fg=$color_border_fg
set -g pane-active-border-style bg=$color_border_active_bg,fg=$color_border_active_fg

# === windows/panes
set -g window-active-style bg=$color_bg_active,fg=$color_fg
set -g window-style bg=$color_bg_inactive,fg=$color_fg

# === statusline

set -g status on
set -g status-justify absolute-centre
set -g status-interval 15
set -g status-position bottom

set -g status-style bg=$color_status_bg,fg=$color_status_fg

set -g window-status-current-format "\
	#[bg=$color_status_bg,fg=$color_window_status_current_bg]\
	#[bg=$color_window_status_current_bg,fg=$color_window_status_current_fg,bold]#I \
	#[bg=$color_badge_bg,fg=$color_badge_fg,nobold] #W#F\
	#[bg=$color_status_bg,fg=$color_badge_bg]"

set -g window-status-format "\
	#[bg=$color_status_bg,fg=$color_window_status_bg]\
	#[bg=$color_window_status_bg,fg=$color_window_status_fg,bold]#I \
	#[bg=$color_badge_bg,fg=$color_badge_fg,nobold] #W#F\
	#[bg=$color_status_bg,fg=$color_badge_bg]"

set -g message-style bg=$color_status_bg,fg=$color_status_fg,align=centre
set -g message-command-style bg=$color_status_bg,bg=$color_status_fg,align=centre

set -g window-status-bell-style fg=white,bg=red,bright
set -g window-status-activity-style fg=blue,bg=white,bright

set -g status-left-length 20
set -g status-left "#[fg=$color_magenta] #S #[fg=$color_status_fg]"

set -g status-right-length 20
set -g status-right "\
	#{?#(echo $SSH_CLIENT),#[fg=$color_orange]󰣀 #H,} \
	#{?mouse,#[fg=$color_orange],#[fg=$color_grey]}󰰏 \
	#{?monitor-activity,#[fg=$color_orange],#[fg=$color_grey]}󰯫 \
	#[fg=$color_magenta]󰔛 %H:%M"

