# vim: set ft=tmux tw=0 nowrap:

# settings for everforest color scheme
#
# palette: https://github.com/sainnhe/everforest/blob/master/palette.md
#

theme_bg_dim="#1e2326"
theme_bg0="#272e33"
theme_bg1="#2e383c"
theme_bg2="#374145"
theme_bg3="#414b50"
theme_bg4="#495156"
theme_bg5="#4f5b58"
theme_bg_visual="#4c3743"
theme_bg_red="#493b40"
theme_bg_yellow="#45443c"
theme_bg_green="#3c4841"
theme_bg_blue="#384b55"
theme_bg_purple="#463f48"

theme_fg="#d3c6aa"
theme_red="#e67e80"
theme_orange="#e69875"
theme_yellow="#dbbc7f"
theme_green="#a7c080"
theme_aqua="#83c092"
theme_blue="#7fbbb3"
theme_purple="#d699b6"

theme_grey0="#7a8478"
theme_grey1="#859289"
theme_grey2="#9da9a0"
theme_statusline1="#a7c080"
theme_statusline2="#d3c6aa"
theme_statusline3="#e67e80"

color_blue=$theme_blue
color_orange=$theme_orange
color_red=$theme_red
color_grey=$theme_grey0

color_fg=$theme_fg
color_bg=$theme_bg1
color_inactive=$theme_bg_dim
color_status=$theme_bg0
color_badge=$theme_bg_blue


color_border=$theme_grey1
color_border_active=$theme_statusline1


# windows/panes
set -g window-active-style "bg=$color_bg,fg=$color_fg"
set -g window-style "bg=$color_inactive,fg=$color_fg"

# statusline
set -g status-style "fg=$color_blue,bg=$color_status"
set -g window-status-current-format "#[fg=$color_orange,bg=$color_status]#[bg=$color_orange,fg=$color_bg]#I #[bg=$color_badge,fg=$color_blue] #W#F#[fg=$color_badge,bg=$color_status]"
set -g window-status-format "#[fg=$color_grey,bg=$color_status]#[bg=$color_grey,fg=$color_bg]#I #[bg=$color_badge,fg=$color_blue] #W#F#[fg=$color_badge,bg=$color_status]"

# inputs when pressed C-b:
set -g message-style "fg=$color_blue,bg=$color_status,align=centre"
set -g message-command-style "fg=$color_blue,bg=$color_status,align=centre"

set -g window-status-bell-style fg=white,bg=red,bright
set -g window-status-activity-style fg=blue,bg=white,bright


set -g pane-border-style bg=terminal,fg=$color_border
set -g pane-active-border-style bg=terminal,fg=$color_border_active
