# vim: set ft=tmux sw=2 ts=2 tw=0 nowrap:

# settings for everforest color scheme
#
# palette: https://github.com/sainnhe/everforest/blob/master/palette.md
#

theme_bg_dim="#232a2e"
theme_bg0="#2d353b"
theme_bg1="#343f44"
theme_bg2="#3d484d"
theme_bg3="#475258"
theme_bg4="#4f585e"
theme_bg5="#56635f"
theme_bg_visual="#543a48"
theme_bg_red="#514045"
theme_bg_yellow="#4d4c43"
theme_bg_green="#425047"
theme_bg_blue="#3a515d"
theme_bg_purple="#4a444e"

theme_fg="#d3c6aa"
theme_red="#e67e80"
theme_orange="#e69875"
theme_yellow="#dbbc7f"
theme_green="#a7c080"
theme_aqua="#83c092"
theme_blue="#7fbbb3"
theme_purple="#d699b6"

theme_grey0="#7a8478"
theme_grey1="#859289"
theme_grey2="#9da9a0"
theme_statusline1="#a7c080"
theme_statusline2="#d3c6aa"
theme_statusline3="#e67e80"

# ----------

color_fg=$theme_fg
color_bg_active=$theme_bg0
color_bg_inactive=$theme_bg2

color_border_bg=$color_bg_inactive
color_border_fg=$theme_grey1
color_border_active_bg=$color_bg_active
color_border_active_fg=$theme_statusline1

color_status_bg=$theme_bg2
color_status_fg=$theme_blue

color_window_status_bg=$theme_grey0
color_window_status_fg=$theme_bg0

color_window_status_current_bg=$theme_green
color_window_status_current_fg=$theme_bg0

color_badge_bg=$theme_bg_blue
color_badge_fg=$theme_blue

color_grey=$theme_grey0
color_orange=$theme_orange
color_magenta=$theme_purple


