# vim: set ft=tmux tw=0 nowrap:

# Define your colors
set -g @theme_color_bg0   "#100f0f"
set -g @theme_color_bg1   "#1c1b1a"
set -g @theme_color_bg2   "#282726"
set -g @theme_color_bg3   "#282726"
set -g @theme_color_fg    "#f2f0e5"

set -g @theme_color_blue    "#0000ff"
set -g @theme_color_orange  "#bc5215"
set -g @theme_color_red     "#d14d41"
set -g @theme_color_grey    "#878580"
set -g @theme_color_magenta "#ce5d97"

color_inactive="#1c1b1a"
color_status="#282726"
color_badge="#575653"


fg_active_window="#{@theme_color_fg}"
bg_active_window="#{@theme_color_fg}"

fg_trigger_on="#{@theme_color_fg}"
fg_trigger_off="#{@theme_color_fg}"

fg_window="#{@theme_color_fg}"
bg_window="#{@theme_color_fg}"

fg_status="#{@theme_color_fg}"
bg_status="#{@theme_color_bg3}"

bg_session="#{@theme_color_bg}"
fg_session="#{@theme_color_fg}"

bg_badge_status="#{@theme_color_bg2}"
fg_badge_status="#{@theme_color_bg2}"

bg_badge_body="#{@theme_color_bg2}"
fg_badge_body="#{@theme_color_fg}"

fg_time="#{@theme_color_magenta}"


set -g status-left-length 40
set -g status-left "#[fg=$fg_status]  #S #{?mouse,#[fg=$fg_trigger_on],#[fg=$fg_trigger_off]}󰰏 #{?monitor-activity,#[fg=$fg_trigger_on],#[fg=$fg_trigger_off]}󰯫 "
set -g status-right-length 40
set -g status-right "#{?#(echo $SSH_CLIENT),#[fg=$fg_trigger_on]󰣀 #H,} #[fg=$fg_time]󰔛 %H:%M "

# windows/panes
set -g window-active-style "bg=$bg_active_window,fg=$fg_active_window"
set -g window-style        "bg=$bg_window,fg=$fg_window"

# statusline
set -g status-style "bg=$bg_status,fg=$fg_status"
set -g window-status-current-format "#[bg=$bg_status,fg=$fg_trigger_on]#[bg=$fg_trigger_on,fg=$bg_badge]#I #[bg=$bg_badge,fg=$fg_badge] #W#F#[bg=$bg_status,fg=$bg_color_badge]"
set -g window-status-format "#[bg=$bg_status,fg=$fg_trigger_off]#[bg=$fg_trigger_off,fg=$bg_badge]#I #[bg=$bg_badge,fg=$fg_badge] #W#F#[bg=$bg_status,fg=$bg_color_badge]"

# inputs when pressed C-b:
set -g message-style "fg=$color_blue,bg=$color_status,align=centre"
set -g message-command-style "fg=$color_blue,bg=$color_status,align=centre"

set -g window-status-bell-style fg=white,bg=red,bright
set -g window-status-activity-style fg=blue,bg=white,bright
