# diasble mouse (see also toggle mouse):
set -g mouse off

# toggle mouse (see also status-right):
bind m set -g mouse \; display "mouse: #{?mouse,on,off}"

# COLORS: status, windows, messages
set -g status-interval 1

set -g status-style bg=terminal,fg=default
set -g window-status-style bg=terminal,fg=default,dim
# colors are taken for the colorscheme rose-pine
set -g window-status-current-style bg=#d7827e,fg=#faf4ed,bold
set -g window-status-activity-style fg=#faf4ed,bg=#286983,bold
set -g window-status-bell-style fg=#faf4ed,bg=#286983,bold

setw -g window-active-style bg=terminal,fg=terminal
setw -g window-style bg=terminal,bright,fg=terminal
set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg=green,bg=default
set -g message-style fg=default,bg=default,bright


set -g status-style default # only bg value is respected

# use vim keys for traversal in selection and copy mode
# (note: not copy and paste from system clipboard)
unbind -Tcopy-mode-vi Space
unbind -Tcopy-mode-vi Enter
bind -Tcopy-mode-vi v send -X begin-selection
bind -Tcopy-mode-vi y send -X copy-selection

# Don't wrap searches; it's super confusing given tmux's reverse-ordering of
# position info in copy mode.
set-option -w -g wrap-search off

# Stay in copy mode on drag end.
# (Would use `bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X
# stop-selection` but it is a bit glitchy.)
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# Scroll 3 lines at a time instead of default 5; don't extend dragged selections.
bind-key -T copy-mode-vi WheelUpPane select-pane\; send-keys -t'{mouse}' -X clear-selection\; send-keys -t'{mouse}' -X -N 3 scroll-up
bind-key -T copy-mode-vi WheelDownPane select-pane\; send-keys -t'{mouse}' -X clear-selection\; send-keys -t'{mouse}' -X -N 3 scroll-down

# Make double and triple click work outside of copy mode (already works inside it with default bindings).
bind-key -T root DoubleClick1Pane if-shell -Ft'{mouse}' '#{alternate_on}' "send-keys -M" "copy-mode -t'{mouse}'; send-keys -t'{mouse}' -X select-word"
bind-key -T root TripleClick1Pane if-shell -Ft'{mouse}' '#{alternate_on}' "send-keys -M" "copy-mode -t'{mouse}'; send-keys -t'{mouse}' -X select-line"

# Don't exit copy mode on double or triple click.
bind-key -T copy-mode-vi DoubleClick1Pane if-shell -Ft'{mouse}' '#{alternate_on}' "send-keys -M" "copy-mode -t'{mouse}'; send-keys -t'{mouse}' -X select-word"
bind-key -T copy-mode-vi TripleClick1Pane if-shell -Ft'{mouse}' '#{alternate_on}' "send-keys -M" "copy-mode -t'{mouse}'; send-keys -t'{mouse}' -X select-line"

# For those times when C-c and q are not enough.
bind-key -T copy-mode-vi Escape send-keys -X cancel
