# diasble mouse (see also toggle mouse):
set -g mouse off

# use vim keys for traversal in selection and copy mode
# (note: not copy and paste from system clipboard)
unbind -Tcopy-mode-vi Space
unbind -Tcopy-mode-vi Enter
bind -Tcopy-mode-vi v send -X begin-selection
bind -Tcopy-mode-vi y send -X copy-selection
bind -Tcopy-mode-vi Escape send -X cancel

# toggle mouse (see also status-right):
bind m set -g mouse \; display "mouse: #{?mouse,on,off}"

# COLORS: status, windows, messages
set -g status-interval 1
set -g status-bg default
set -g status-fg magenta
setw -g window-active-style bg=terminal,fg=terminal
setw -g window-style bg=terminal,bright,fg=terminal
setw -g window-status-style fg=blue,bg=default,dim
setw -g window-status-current-style fg=brightred,bg=default,bright
setw -g window-status-bell-style fg=white,bg=red,bright
setw -g window-status-activity-style fg=blue,bg=white,bright
set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg=green,bg=default
set -g message-style fg=default,bg=default,bright
set -g status-style default
