set   -g base-index 1               # enumerate windows starting from 1
setw  -g pane-base-index 1          # enumerate panes starting from 1
set  -sg escape-time 1              # set no delay for escape key press

# set terminal window title to be a name of tmux window
set-option -g set-titles on
set-option -g set-titles-string "#S / #W"

# new window while keeping current path C-b-c
bind-key c   new-window   -c "#{pane_current_path}"
# new horisontal pane while keeping current path C-b-%
bind-key %   split-window -h -c "#{pane_current_path}"
# new vertical pane while keeping current path C-b-"
bind-key '"' split-window -v -c "#{pane_current_path}"

# vim keybindings for panes traversal
unbind Left
unbind Down
unbind Up
unbind Right
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# do not monitor activity by default to avoid additional distractions
set -g monitor-activity off
# toggle activity monitor using C-b-a
bind a set -w monitor-activity\; display "monitor-activity: #{?monitor-activity,on,off}"

# reload tmux config file using C-b-r
bind M-r source-file ~/.tmux.conf \; display-message "reloading config"
 
 # fix window numbers (when you have closed some windows and numbers are odd) using C-b-w
bind M-w  move-window -r \; display-message "fixing window numbers"
 
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n M-h if-shell "$is_vim" "send-keys M-h"  "select-pane -L"
bind-key -n M-j if-shell "$is_vim" "send-keys M-j"  "select-pane -D"
bind-key -n M-k if-shell "$is_vim" "send-keys M-k"  "select-pane -U"
bind-key -n M-l if-shell "$is_vim" "send-keys M-l"  "select-pane -R"
bind-key -T copy-mode-vi M-h select-pane -L
bind-key -T copy-mode-vi M-j select-pane -D
bind-key -T copy-mode-vi M-k select-pane -U
bind-key -T copy-mode-vi M-l select-pane -R
# turn on focus events reporting to focus detection in vim
set -g focus-events on
 
# status left
set -g status-left "#[fg=purple]▶ #S "
set -g status-left-length 48
 
# status right
set -g status-right "#[fg=purple]▶ %a %d %b %T"
set -g status-right-length 100
set -g status-justify centre
 
# status window
setw -g window-status-current-format " #[bold]#I:#W#F "
setw -g window-status-format " #I:#W#F "
setw -g alternate-screen on
setw -g window-status-current-style reverse
 
# automatic window renaming (title)
setw -g automatic-rename on
setw -g automatic-rename-format "#{pane_current_command}"
 
# defautl tmux terminal settings
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
