return {
  "nvim-treesitter/nvim-treesitter",
  lazy   = false,
  build  = ":TSUpdate",
  config = function()
    require("nvim-treesitter.configs").setup({
      modules = {},
      ensure_installed = {
        "go",
        "gomod",
        "gosum",
        "gowork",
        "html",
        "json",
        "jq",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "dockerfile",
        "vim",
        "vimdoc",
        "sql",
        "python",
        "bash",
        "rust",
      },
      ignore_install = {},
      sync_install = false,
      auto_install = true,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
}
