console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true
auto_upgrade = true

[secondary_prompt]
template = " "
foreground = 'magenta'
background = 'transparent'

[transient_prompt]
template = " "
background = 'transparent'
foreground_templates = [
	'{{if gt .Code 0}}red{{end}}',
	'{{if eq .Code 0}}magenta{{end}}',
]

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "blue"
background = "transparent"
template = '{{ .Path }}'
[blocks.segments.cache]
duration = "1m"
strategy = "folder"
[blocks.segments.properties]
style = "full"
[blocks.segments.properties.mapped_locations]
"~/code/github.com/*" = "github.com"
"~/code/gilab.com/*" = "gitlab.com"

[[blocks.segments]]
type = "git"
style = "plain"
foreground = 'p:grey'
background = "transparent"
template = """ {{ .HEAD }}
{{- if or (.Working.Changed) (.Staging.Changed) }} ∗ {{- end -}}
{{- if .BranchStatus -}}
<cyan>
	{{- if gt .Behind 0 -}}⇣ {{- end -}}
	{{- if gt .Ahead 0  -}}⇡ {{- end -}}
</>
{{- end }} """
[blocks.segments.cache]
duration = "none"
[blocks.segments.properties]
commit_icon = '@'
fetch_status = true

[[blocks]]
type = "rprompt"
alignment = "right"
overflow = "hidden"

# add more languages here
[[blocks.segments]]
type = "go"
style = "plain"
foreground = "blue"
background = "transparent"
template = "  {{ .Full }} "
[blocks.segments.properties]
cache_duration = "1m"

[[blocks.segments]]
type = "lua"
style = "plain"
foreground = "blue"
background = "transparent"
template = "  {{ .Full }} "
[blocks.segments.properties]
cache_duration = "1m"

[[blocks.segments]]
type = "rust"
style = "plain"
foreground = "blue"
background = "transparent"
template = "  {{ .Full }} "
[blocks.segments.properties]
cache_duration = "1m"


[[blocks]]
type = "prompt"
alignment = "right"

[[blocks.segments]]
type = "text"
style = "plain"
foreground = 'yellow'
background = 'transparent'
template = """
{{- if .Env.YAZI_LEVEL -}}
 {{ .Env.YAZI_LEVEL }}
{{- end -}}
"""
[blocks.segments.cache]
duration = "none"

[[blocks.segments]]
type = "status"
style = "plain"
foreground = "red"
background = "transparent"
template = "  {{ .String }}"
[blocks.segments.properties]
cache_duration = "none"
threshold = 1000

[[blocks.segments]]
type = "executiontime"
style = 'plain'
foreground = "magenta"
background = "transparent"
template = " 󰔛 {{ .FormattedMs }}"
[blocks.segments.properties]
cache_duration = "none"
threshold = 1000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
background = 'transparent'
foreground_templates = [
	'{{if gt .Code 0}}red{{end}}',
	'{{if eq .Code 0}}magenta{{end}}',
]
template = ""
[blocks.segments.properties]
cache_duration = 'none'
