#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "weirdgiraffe"
email = "giraffe@cyberzoo.xyz"
[user.signing]
behavior = "own"
backend = "gpg"

[ui]
default-command = ["log", "-n", "5"]
show-cryptographic-signatures = true

[aliases]
e = ["edit"]
l = ["log"]
st = ["status"]
d = ["describe"]
