#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "weirdgiraffe"
email = "giraffe@cyberzoo.xyz"

[aliases]
e = ["edit"]
l = ["log", "-n", "10"]
st = ["status"]
d = ["describe"]
