name: Check OSX configuration
run-name: Test OSX dotfiles
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure zsh
        run: |
          make zsh
      - name: output resuting config
        run: cat ~/.zshrc
